spring.application.name=TH06876_JAVA202

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhthth06876@gmail.com
spring.mail.password=benuvvynvflgqbap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# GHN API Configuration - ?Ã C?P NH?T ??Y ??
# Token API c?a b?n: 57410436-7390-11f1-af48-0a90b7d043e3
# Shop ID: 2511863 (t? ?nh tr??c)
# ??a ch? shop: 123 Hoàng Hoa Thám, Ba ?ình, Hà N?i
ghn.api.url=https://online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee
ghn.api.token=57410436-7390-11f1-af48-0a90b7d043e3
ghn.shop.id=6518472
ghn.shop.district.id=1442
ghn.shop.ward.code=1A0401
ghn.shop.address=123 Hoàng Hoa Thám
ghn.shop.province.id=201    

# VNPay Configuration
vietqr.bank=MB
vietqr.account=0344552008
vietqr.account-name=Truong%20Hai%20Minh
#vnpay.tmn-code=YOUR_TMN_CODE
#vnpay.hash-secret=YOUR_SECRET_KEY
#vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.return-url=http://localhost:8080/banhang/vnpay_return
#vnpay.version=2.1.0
#vnpay.command=pay
#vnpay.currency=VND
#vnpay.locale=vn
#vnpay.order-type=billpayment

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Duantotnghiep
spring.datasource.username=sa
spring.datasource.password=1234

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# spring.jpa.hibernate.ddl-auto=update

# Session
server.tomcat.max-part-count=100
spring.session.store-type=jdbc  
spring.session.jdbc.initialize-schema=always
spring.session.timeout=30d

# Upload file
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB
server.tomcat.connection-timeout=60000

# Static resources
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/