spring.application.name=TH06876_JAVA202

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhthth06876@gmail.com
spring.mail.password=benuvvynvflgqbap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Duantotnghiep
spring.datasource.username=sa
spring.datasource.password=1234
# Session

server.tomcat.max-part-count=100
spring.session.store-type=jdbc  
spring.session.jdbc.initialize-schema=always
spring.session.timeout=30d

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB
server.tomcat.connection-timeout=60000

spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/